MVCBlog/Controllers/AdminBlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCBlog.Models;
using System.Web.Helpers;
using System.IO;
using System.Text.RegularExpressions;

namespace MVCBlog.Controllers
{
    public class AdminBlogController : Controller
    {
        DBBlogEntities db = new DBBlogEntities();
        // GET: AdminBlog
        public ActionResult Index()
        {
            var blogs = db.Blogs.ToList();
            return View(blogs);
        }

        // GET: AdminBlog/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);

            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // GET: AdminBlog/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminBlog/Create
        [HttpPost]
        public ActionResult Create(Blog blog, HttpPostedFileBase foto)
        {
            try
            {
                if (foto != null)
                {
                    WebImage webImage = new WebImage(foto.InputStream);
                    FileInfo fileInfo = new FileInfo(foto.FileName);
                    string newFoto = Guid.NewGuid().ToString() + fileInfo.Extension;
                    webImage.Resize(800, 350);
                    webImage.Save("~/Uploads/" + newFoto);
                    blog.Foto = "/Uploads/" + newFoto;

                }
                blog.BlogOkunmaSayisi = 0;
                blog.BlogTarih = DateTime.Now;
                db.Blogs.Add(blog);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: AdminBlog/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }

            var blog = db.Blogs.Find(id);
            return View(blog);
        }

        // POST: AdminBlog/Edit/5
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(int id, FormCollection collection, HttpPostedFileBase foto, Blog blog)
        {
            try
            {
                var blogUpdate = db.Blogs.Find(id);

                if (foto != null)
                {
                    if (System.IO.File.Exists(Server.MapPath(blog.Foto)))
                    {
                        System.IO.File.Delete(Server.MapPath(blog.Foto));
                    }

                    WebImage webImage = new WebImage(foto.InputStream);
                    FileInfo fileInfo = new FileInfo(foto.FileName);
                    string newFoto = Guid.NewGuid().ToString() + fileInfo.Extension;
                    webImage.Resize(800, 350);
                    webImage.Save("~/Uploads/" + newFoto);
                    blogUpdate.Foto = "/Uploads/" + newFoto;

                    blogUpdate.BlogBaslik = blog.BlogBaslik;
                    blogUpdate.BlogIcerik = blog.BlogIcerik;
                    blogUpdate.BlogOkunmaSayisi = blog.BlogOkunmaSayisi;
                    blogUpdate.BlogOkunmaSuresi = blog.BlogOkunmaSuresi;
                    db.SaveChanges();

                    return RedirectToAction("Index");
                } else
                {
                    blogUpdate.BlogBaslik = blog.BlogBaslik;
                    blogUpdate.BlogIcerik = blog.BlogIcerik;
                    blogUpdate.BlogOkunmaSayisi = blog.BlogOkunmaSayisi;
                    blogUpdate.BlogOkunmaSuresi = blog.BlogOkunmaSuresi;
                    db.SaveChanges();
                }

                return View();

            }
            catch
            {
                return View();
            }
        }

        // GET: AdminBlog/Delete/5
        public ActionResult Delete(int id)
        {
            var blog = db.Blogs.Where(b => b.BlogID == id).SingleOrDefault();
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // POST: AdminBlog/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                var blog = db.Blogs.Where(b => b.BlogID == id).SingleOrDefault();
                if (blog == null)
                {
                    return HttpNotFound();
                }
                if (System.IO.File.Exists(Server.MapPath(blog.Foto)))
                {
                    System.IO.File.Delete(Server.MapPath(blog.Foto));
                }
                db.Blogs.Remove(blog);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        protected string StripHtml(string Txt)
        {
            return Regex.Replace(Txt, "<(.|\\n)*?>", string.Empty);
        }
    }
}

MVCBlog/Views/AdminBlog/Create.cshtml
@model MVCBlog.Models.Blog

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Yeni Blog Oluştur</h2>


@using (Html.BeginForm("Create", "AdminBlog", FormMethod.Post, new { enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Blog</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BlogBaslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BlogBaslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BlogBaslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BlogIcerik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BlogIcerik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BlogIcerik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Foto" accept=".jpg,.jpeg,.png,.JPG,.JPEG"/>
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BlogOkunmaSuresi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BlogOkunmaSuresi, new { htmlAttributes = new { @class = "form-control", @placeholder="Dakika olarak giriniz"} })
                @Html.ValidationMessageFor(model => model.BlogOkunmaSuresi, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Oluştur" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Geri Dön", "Index")
</div>

MVCBlog/Views/AdminBlog/Delete.cshtml
@model MVCBlog.Models.Blog

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Sil</h2>

<h3>Emin misin?</h3>
<div>
    <h4>Blog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BlogBaslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BlogBaslik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BlogIcerik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BlogIcerik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Foto)
            <img class="img-responsive" width="75" src="@Model.Foto" alt=".."/>
        </dt>

        @*<dd>
            @Html.DisplayFor(model => model.Foto)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.BlogOkunmaSayisi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BlogOkunmaSayisi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BlogOkunmaSuresi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BlogOkunmaSuresi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BlogTarih)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BlogTarih)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVCBlog/Views/AdminBlog/Details.cshtml
@model MVCBlog.Models.Blog

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div>
    <h4>Detay</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BlogBaslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BlogBaslik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BlogIcerik)
        </dt>

        <dd>
            @Html.Raw(Model.BlogIcerik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Foto)
            <img class="img-responsive" width="75" src="@Model.Foto" alt=".." />
        </dt>

        <dt>
            @Html.DisplayNameFor(model => model.BlogOkunmaSayisi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BlogOkunmaSayisi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BlogOkunmaSuresi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BlogOkunmaSuresi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BlogTarih)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BlogTarih)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Güncelle", "Edit", new { id = Model.BlogID }) |
    @Html.ActionLink("Listeye Geri Dön", "Index")
</p>

MVCBlog/Views/AdminBlog/Edit.cshtml
@model MVCBlog.Models.Blog

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "AdminBlog", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Blog</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.BlogID)

    <div class="form-group">
        @Html.LabelFor(model => model.BlogBaslik, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BlogBaslik, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BlogBaslik, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BlogIcerik, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BlogIcerik, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BlogIcerik, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Foto, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
        </div>
    </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <img class="img-responsive" width="75" src="@Model.Foto" alt=".." />
            <input type="file" name="Foto" accept=".jpg,.jpeg,.png,.JPG,.JPEG" />
            @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BlogOkunmaSayisi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BlogOkunmaSayisi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BlogOkunmaSayisi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BlogOkunmaSuresi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BlogOkunmaSuresi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BlogOkunmaSuresi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BlogTarih, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BlogTarih, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BlogTarih, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVCBlog/Views/AdminBlog/Index.cshtml
@model IEnumerable<MVCBlog.Models.Blog>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<p>
    @Html.ActionLink("Yeni Oluştur", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BlogBaslik)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.BlogIcerik)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Foto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BlogOkunmaSayisi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BlogOkunmaSuresi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BlogTarih)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.BlogBaslik)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.BlogIcerik)
        </td>*@
        <td>
            <img class="img-responsive" width="75" src="@item.Foto" alt=".."/>
            @*@Html.DisplayFor(modelItem => item.Foto)*@
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BlogOkunmaSayisi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BlogOkunmaSuresi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BlogTarih)
        </td>
        <td>
            @Html.ActionLink("Güncelle", "Edit", new { id=item.BlogID }) |
            @Html.ActionLink("Ayrıntılar", "Details", new { id=item.BlogID }) |
            @Html.ActionLink("Sil", "Delete", new { id=item.BlogID })
        </td>
    </tr>
}

</table>